name: Newman run

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dir for report
        run: |
          mkdir testArtifacts
      
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13'
      
      - name: Install Newman
        run: |
             npm install -g newman 
             npm install -g newman-reporter-htmlextra
      
      - name: Run test
        run: newman run serverest.postman_collection.json -e ServeRest.postman_environment.json -r cli,htmlextra

      - name: Report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Report
          path: newman
